version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
