version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.75'
        reservations:
          memory: 1024M
          cpus: '0.75'
  external_api:
      build:
          context: ./external_api
          dockerfile: Dockerfile
      ports:
          - "5001:5001"
#      env_file:
#          - .env
      depends_on:
          - db

  server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod} # Debug purposes
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 1024M
          cpus: '0.75'

volumes:
  postgres_data:
    driver: local
