#!/bin/sh

echo "⚙️ Formatting code with ktlintFormat..."
./gradlew ktlintFormat
STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "🚫 ktlintFormat failed. Aborting commit."
  exit $STATUS
fi
# Stage any formatting changes
git add -A