name: CI

on:
  push:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build_and_lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}

      - name: Build (assemble, skip tests)
        run: ./gradlew assemble -x test

      - name: Run linter & formatting check (ktlint)
        run: ./gradlew ktlintCheck
