name: Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
      - 'v*.*.*-dev'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Determine branch and bump version
        run: |
          git fetch origin main dev
          if [[ "${GITHUB_REF#refs/tags/}" == *-dev ]]; then
            BRANCH="dev"
          else
            BRANCH="main"
          fi
          git checkout $BRANCH
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          VERSION=${VERSION%-dev}
          sed -i "s/version = '.*'/version = '$VERSION'/" build.gradle
          echo "Version bumped to $VERSION on branch $BRANCH"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install GitHub Changelog Generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          github_changelog_generator --future-release $RELEASE_TAG --no-unreleased

      - name: Commit version and changelog
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add build.gradle CHANGELOG.md
          git commit -m "chore(release): ${GITHUB_REF#refs/tags/}" || echo "Nothing to commit"
          git push origin $BRANCH

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ endsWith(github.ref_name, '-dev') }}
          generate_release_notes: true 