name: Unit Tests

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  run_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Execute Unit Tests
    runs-on: ubuntu-latest

    env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '24'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}

      - name: Run unit tests
        run: ./gradlew test
